### ISSUE TITLE
building for leia 18.2.3 on OSX succeeds but install from zip fails

### ISSUE THREAD

**Issue by bendschs** [rbuehlma/pvr.teleboy#57]
like described in the title i was able to build but unfortunately installing the zip fails with unspecific message.

during cmake i got the following warning:

```
CMake Warning (dev) at /Users/xxy/xbmc/cmake/scripts/common/HandleDepends.cmake:220 (message):
  /Users/xxy/pvr.teleboy/depends/common/rapidjson/rapidjson.sha256 is
  missing
```

What am i missing here?

Cheers
Bendsch

**Comment by rbuehlma** [comment]
This Warning should not be the cause but did you build the Leia branch of the Addon? You will also need to use the Leia source of Kodi. And you should also provide the Kodi log while trying to install the zip. There should be more information in there.

**Comment by bendschs** [comment]
logfile shows that kodi is looking for some files in the general /Users/shared folder during install. i don't know what this should be the case?
```
2020-08-05 02:00:25.577 T:123145506889728  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device HP ZR2440w
2020-08-05 02:00:26.194 T:123145509036032 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-08-05 02:00:26.652 T:123145509036032  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
2020-08-05 02:01:07.926 T:123145537744896   ERROR: Traceback (most recent call last):
2020-08-05 02:01:07.927 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 86, in run
2020-08-05 02:01:07.927 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
2020-08-05 02:01:07.927 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 212, in write
2020-08-05 02:01:07.927 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
2020-08-05 02:01:07.927 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 197, in send_preamble
2020-08-05 02:01:07.927 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/socket.py", line 328, in write
2020-08-05 02:01:07.928 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/socket.py", line 307, in flush
2020-08-05 02:01:07.928 T:123145537744896   ERROR: error: [Errno 32] Broken pipe
2020-08-05 02:01:07.928 T:123145541951488   ERROR: Traceback (most recent call last):
2020-08-05 02:01:07.928 T:123145541951488   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 86, in run
2020-08-05 02:01:07.928 T:123145537744896   ERROR: Traceback (most recent call last):
2020-08-05 02:01:07.928 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-08-05 02:01:07.928 T:123145541951488   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
2020-08-05 02:01:07.929 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-08-05 02:01:07.929 T:123145541951488   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 212, in write
2020-08-05 02:01:07.929 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/SocketServer.py", line 654, in __init__
2020-08-05 02:01:07.929 T:123145541951488   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
2020-08-05 02:01:07.929 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/SocketServer.py", line 713, in finish
2020-08-05 02:01:07.929 T:123145541951488   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/wsgiref/handlers.py", line 197, in send_preamble
2020-08-05 02:01:07.929 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/socket.py", line 283, in close
2020-08-05 02:01:07.929 T:123145541951488   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/socket.py", line 328, in write
2020-08-05 02:01:07.929 T:123145537744896   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64_Leia/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/socket.py", line 307, in flush
2020-08-05 02:01:07.929 T:123145537744896   ERROR: Previous line repeats 1 times.
2020-08-05 02:01:07.929 T:123145537744896   ERROR: error: [Errno 32] Broken pipe

```

**Comment by rbuehlma** [comment]
Unfortunately, I do not know the build process well enough to help here. But since most the the build is part of Kodi anyway, you might want to ask in their forum.
